spring:
  application:
    name: config-service

---
spring:
  profiles: development
  application:
    name: config-service
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
