spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: DEBUG


custom:
  property: dev-value
datasource:
  url: jdbc:mysql://localhost:3306/dev_db
  username: dev_user
  password: dev_password
